In [62]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix

In [63]:
ratings = pd.read_csv('ml-latest-small/ratings.csv', sep=',', engine='python')
ratings.head()

   userId  movieId  rating  timestamp
0       1        1   4.000  964982703
1       1        3   4.000  964981247
2       1        6   4.000  964982224
3       1       47   5.000  964983815
4       1       50   5.000  964982931

In [64]:
movieCols = ['MovieID','Title','Genres']
movies = pd.read_csv('ml-latest-small/movies.csv', sep=',', engine='python')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [65]:
Add_names_to_ratings_table = pd.merge(ratings,movies,on='movieId')
drop_col = ['timestamp', 'genres']
# Add_names_to_users_table.head()
# drop
Add_names_to_ratings_table = Add_names_to_ratings_table.drop(drop_col,axis=1)
Add_names_to_ratings_table.head()

   userId  movieId  rating             title
0       1        1   4.000  Toy Story (1995)
1       5        1   4.000  Toy Story (1995)
2       7        1   4.500  Toy Story (1995)
3      15        1   2.500  Toy Story (1995)
4      17        1   4.500  Toy Story (1995)

In [66]:
Add_names_to_ratings_table = Add_names_to_ratings_table.dropna(axis = 0, subset=['title'])

In [67]:
movie_ratingCount = (Add_names_to_ratings_table.groupby(by = ['title'])['rating'].count().reset_index())
movie_ratingCount.columns = ['title','totalRating']
movie_ratingCount.head()

                                     title  totalRating
0                               '71 (2014)            1
1  'Hellboy': The Seeds of Creation (2004)            1
2                   'Round Midnight (1986)            2
3                      'Salem's Lot (2004)            1
4                'Til There Was You (1997)            2

In [68]:
rating_with_totalRating = Add_names_to_ratings_table.merge(movie_ratingCount,left_on='title',right_on='title',how='left')
rating_with_totalRating.head()

   userId  movieId  rating             title  totalRating
0       1        1   4.000  Toy Story (1995)          215
1       5        1   4.000  Toy Story (1995)          215
2       7        1   4.500  Toy Story (1995)          215
3      15        1   2.500  Toy Story (1995)          215
4      17        1   4.500  Toy Story (1995)          215

In [69]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(movie_ratingCount['totalRating'].describe())

count   9719.000
mean      10.375
std       22.406
min        1.000
25%        1.000
50%        3.000
75%        9.000
max      329.000
Name: totalRating, dtype: float64

In [70]:
threshold = 25
rating_popular_movie = movie_ratingCount.query('totalRating >= @threshold').sort_values('title')
print(rating_popular_movie)

                                                  title  totalRating
8                           (500) Days of Summer (2009)           42
18                    10 Things I Hate About You (1999)           54
23                                101 Dalmatians (1996)           47
24    101 Dalmatians (One Hundred and One Dalmatians...           44
34                                  12 Angry Men (1957)           57
48                             13th Warrior, The (1999)           26
49                                          1408 (2007)           25
74                         2001: A Space Odyssey (1968)          109
80                                      21 Grams (2003)           25
81                                21 Jump Street (2012)           26
88                                       28 Days (2000)           25
89                                 28 Days Later (2002)           58
104                                          300 (2007)           80
111                                 3:10 to Yuma (2007)           25
115                      40-Year-Old Virgin, The (2005)           74
126                               50 First Dates (2004)           47
139                                       8 Mile (2002)           41
178                 A.I. Artificial Intelligence (2001)           56
191                                About Schmidt (2002)           26
193                                  About a Boy (2002)           44
202                                   Abyss, The (1989)           62
207                   Ace Ventura: Pet Detective (1994)          161
208               Ace Ventura: When Nature Calls (1995)           88
221                                   Adaptation (2002)           46
223                         Addams Family Values (1993)           84
224                           Addams Family, The (1991)           38
244   Adventures of Priscilla, Queen of the Desert, ...           36
261                           African Queen, The (1951)           34
285                                Air Force One (1997)           58
289                                     Airheads (1994)           26
...                                                 ...          ...
9403                     While You Were Sleeping (1995)           98
9407                                    Whiplash (2014)           38
9433                    Who Framed Roger Rabbit? (1988)           97
9442                       Whole Nine Yards, The (2000)           42
9476                                 Wild Things (1998)           31
9477                              Wild Wild West (1999)           53
9483        William Shakespeare's Romeo + Juliet (1996)           36
9484                                      Willow (1988)           40
9485         Willy Wonka & the Chocolate Factory (1971)          119
9534                                     Witness (1985)           40
9537                           Wizard of Oz, The (1939)           92
9547                    Wolf of Wall Street, The (2013)           54
9581                    World Is Not Enough, The (1999)           39
9598                               Wrestler, The (2008)           34
9613              X-Files: Fight the Future, The (1998)           42
9615                                       X-Men (2000)          133
9616                    X-Men Origins: Wolverine (2009)           26
9618                  X-Men: Days of Future Past (2014)           30
9619                          X-Men: First Class (2011)           43
9620                       X-Men: The Last Stand (2006)           52
9621                            X2: X-Men United (2003)           76
9632                                     Yes Man (2008)           34
9651                             You've Got Mail (1998)           50
9656                          Young Frankenstein (1974)           69
9657                                  Young Guns (1988)           25
9695                                      Zodiac (2007)           38
9699                                  Zombieland (2009)           53
9703                                   Zoolander (2001)           54
9707                                    Zootopia (2016)           32
9717                             Â¡Three Amigos! (1986)           26

[1050 rows x 2 columns]

In [111]:
rating_with_totalRating_pivot = rating_with_totalRating.pivot_table(index='title',columns='userId',values='rating'
                                                                    ,aggfunc=np.mean).fillna(0)
rating_with_totalRating_matrix = csr_matrix(rating_with_totalRating_pivot.values)
print(rating_with_totalRating_pivot)

userId                                               1     2     3     4    \
title
'71 (2014)                                         0.000 0.000 0.000 0.000
'Hellboy': The Seeds of Creation (2004)            0.000 0.000 0.000 0.000
'Round Midnight (1986)                             0.000 0.000 0.000 0.000
'Salem's Lot (2004)                                0.000 0.000 0.000 0.000
'Til There Was You (1997)                          0.000 0.000 0.000 0.000
'Tis the Season for Love (2015)                    0.000 0.000 0.000 0.000
'burbs, The (1989)                                 0.000 0.000 0.000 0.000
'night Mother (1986)                               0.000 0.000 0.000 0.000
(500) Days of Summer (2009)                        0.000 0.000 0.000 0.000
*batteries not included (1987)                     0.000 0.000 0.000 0.000
...All the Marbles (1981)                          0.000 0.000 0.000 0.000
...And Justice for All (1979)                      0.000 0.000 0.000 0.000
00 Schneider - Jagd auf Nihil Baxter (1994)        0.000 0.000 0.000 0.000
1-900 (06) (1994)                                  0.000 0.000 0.000 0.000
10 (1979)                                          0.000 0.000 0.000 0.000
10 Cent Pistol (2015)                              0.000 0.000 0.000 0.000
10 Cloverfield Lane (2016)                         0.000 0.000 0.000 0.000
10 Items or Less (2006)                            0.000 0.000 0.000 0.000
10 Things I Hate About You (1999)                  0.000 0.000 0.000 0.000
10 Years (2011)                                    0.000 0.000 0.000 0.000
10,000 BC (2008)                                   0.000 0.000 0.000 0.000
100 Girls (2000)                                   0.000 0.000 0.000 0.000
100 Streets (2016)                                 0.000 0.000 0.000 0.000
101 Dalmatians (1996)                              0.000 0.000 0.000 0.000
101 Dalmatians (One Hundred and One Dalmatians)... 0.000 0.000 0.000 0.000
101 Dalmatians II: Patch's London Adventure (2003) 0.000 0.000 0.000 0.000
101 Reykjavik (101 ReykjavÃ­k) (2000)              0.000 0.000 0.000 0.000
102 Dalmatians (2000)                              0.000 0.000 0.000 0.000
10th & Wolf (2006)                                 0.000 0.000 0.000 0.000
10th Kingdom, The (2000)                           0.000 0.000 0.000 0.000
...                                                  ...   ...   ...   ...
Zero Dark Thirty (2012)                            0.000 0.000 0.000 0.000
Zero Effect (1998)                                 0.000 0.000 0.000 0.000
Zero Theorem, The (2013)                           0.000 0.000 0.000 0.000
Zero de conduite (Zero for Conduct) (ZÃ©ro de c... 0.000 0.000 0.000 0.000
Zeus and Roxanne (1997)                            0.000 0.000 0.000 0.000
Zipper (2015)                                      0.000 0.000 0.000 0.000
Zodiac (2007)                                      0.000 0.000 0.000 0.000
Zombeavers (2014)                                  0.000 0.000 0.000 0.000
Zombie (a.k.a. Zombie 2: The Dead Are Among Us)... 0.000 0.000 0.000 0.000
Zombie Strippers! (2008)                           0.000 0.000 0.000 0.000
Zombieland (2009)                                  0.000 3.000 0.000 0.000
Zone 39 (1997)                                     0.000 0.000 0.000 0.000
Zone, The (La Zona) (2007)                         0.000 0.000 0.000 0.000
Zookeeper (2011)                                   0.000 0.000 0.000 0.000
Zoolander (2001)                                   0.000 0.000 0.000 0.000
Zoolander 2 (2016)                                 0.000 0.000 0.000 0.000
Zoom (2006)                                        0.000 0.000 0.000 0.000
Zoom (2015)                                        0.000 0.000 0.000 0.000
Zootopia (2016)                                    0.000 0.000 0.000 0.000
Zulu (1964)                                        0.000 0.000 0.000 0.000
Zulu (2013)                                        0.000 0.000 0.000 0.000
[REC] (2007)                                       0.000 0.000 0.000 0.000
[REC]Â² (2009)                                     0.000 0.000 0.000 0.000
[REC]Â³ 3 GÃ©nesis (2012)                          0.000 0.000 0.000 0.000
anohana: The Flower We Saw That Day - The Movie... 0.000 0.000 0.000 0.000
eXistenZ (1999)                                    0.000 0.000 0.000 0.000
xXx (2002)                                         0.000 0.000 0.000 0.000
xXx: State of the Union (2005)                     0.000 0.000 0.000 0.000
Â¡Three Amigos! (1986)                             4.000 0.000 0.000 0.000
Ã€ nous la libertÃ© (Freedom for Us) (1931)        0.000 0.000 0.000 0.000

userId                                               5     6     7     8    \
title
'71 (2014)                                         0.000 0.000 0.000 0.000
'Hellboy': The Seeds of Creation (2004)            0.000 0.000 0.000 0.000
'Round Midnight (1986)                             0.000 0.000 0.000 0.000
'Salem's Lot (2004)                                0.000 0.000 0.000 0.000
'Til There Was You (1997)                          0.000 0.000 0.000 0.000
'Tis the Season for Love (2015)                    0.000 0.000 0.000 0.000
'burbs, The (1989)                                 0.000 0.000 0.000 0.000
'night Mother (1986)                               0.000 0.000 0.000 0.000
(500) Days of Summer (2009)                        0.000 0.000 0.000 0.000
*batteries not included (1987)                     0.000 0.000 0.000 0.000
...All the Marbles (1981)                          0.000 0.000 0.000 0.000
...And Justice for All (1979)                      0.000 0.000 0.000 0.000
00 Schneider - Jagd auf Nihil Baxter (1994)        0.000 0.000 0.000 0.000
1-900 (06) (1994)                                  0.000 0.000 0.000 0.000
10 (1979)                                          0.000 0.000 0.000 0.000
10 Cent Pistol (2015)                              0.000 0.000 0.000 0.000
10 Cloverfield Lane (2016)                         0.000 0.000 0.000 0.000
10 Items or Less (2006)                            0.000 0.000 0.000 0.000
10 Things I Hate About You (1999)                  0.000 0.000 0.000 0.000
10 Years (2011)                                    0.000 0.000 0.000 0.000
10,000 BC (2008)                                   0.000 0.000 0.000 0.000
100 Girls (2000)                                   0.000 0.000 0.000 0.000
100 Streets (2016)                                 0.000 0.000 0.000 0.000
101 Dalmatians (1996)                              0.000 0.000 0.000 0.000
101 Dalmatians (One Hundred and One Dalmatians)... 0.000 0.000 0.000 0.000
101 Dalmatians II: Patch's London Adventure (2003) 0.000 0.000 0.000 0.000
101 Reykjavik (101 ReykjavÃ­k) (2000)              0.000 0.000 0.000 0.000
102 Dalmatians (2000)                              0.000 0.000 0.000 0.000
10th & Wolf (2006)                                 0.000 0.000 0.000 0.000
10th Kingdom, The (2000)                           0.000 0.000 0.000 0.000
...                                                  ...   ...   ...   ...
Zero Dark Thirty (2012)                            0.000 0.000 0.000 0.000
Zero Effect (1998)                                 0.000 0.000 0.000 0.000
Zero Theorem, The (2013)                           0.000 0.000 0.000 0.000
Zero de conduite (Zero for Conduct) (ZÃ©ro de c... 0.000 0.000 0.000 0.000
Zeus and Roxanne (1997)                            0.000 0.000 0.000 0.000
Zipper (2015)                                      0.000 0.000 0.000 0.000
Zodiac (2007)                                      0.000 0.000 0.000 0.000
Zombeavers (2014)                                  0.000 0.000 0.000 0.000
Zombie (a.k.a. Zombie 2: The Dead Are Among Us)... 0.000 0.000 0.000 0.000
Zombie Strippers! (2008)                           0.000 0.000 0.000 0.000
Zombieland (2009)                                  0.000 0.000 0.000 0.000
Zone 39 (1997)                                     0.000 0.000 0.000 0.000
Zone, The (La Zona) (2007)                         0.000 0.000 0.000 0.000
Zookeeper (2011)                                   0.000 0.000 0.000 0.000
Zoolander (2001)                                   0.000 0.000 0.000 0.000
Zoolander 2 (2016)                                 0.000 0.000 0.000 0.000
Zoom (2006)                                        0.000 0.000 0.000 0.000
Zoom (2015)                                        0.000 0.000 0.000 0.000
Zootopia (2016)                                    0.000 0.000 0.000 0.000
Zulu (1964)                                        0.000 0.000 0.000 0.000
Zulu (2013)                                        0.000 0.000 0.000 0.000
[REC] (2007)                                       0.000 0.000 0.000 0.000
[REC]Â² (2009)                                     0.000 0.000 0.000 0.000
[REC]Â³ 3 GÃ©nesis (2012)                          0.000 0.000 0.000 0.000
anohana: The Flower We Saw That Day - The Movie... 0.000 0.000 0.000 0.000
eXistenZ (1999)                                    0.000 0.000 0.000 0.000
xXx (2002)                                         0.000 0.000 0.000 0.000
xXx: State of the Union (2005)                     0.000 0.000 0.000 0.000
Â¡Three Amigos! (1986)                             0.000 0.000 0.000 0.000
Ã€ nous la libertÃ© (Freedom for Us) (1931)        0.000 0.000 0.000 0.000

userId                                               9     10   ...    601  \
title                                                           ...
'71 (2014)                                         0.000 0.000  ...  0.000
'Hellboy': The Seeds of Creation (2004)            0.000 0.000  ...  0.000
'Round Midnight (1986)                             0.000 0.000  ...  0.000
'Salem's Lot (2004)                                0.000 0.000  ...  0.000
'Til There Was You (1997)                          0.000 0.000  ...  0.000
'Tis the Season for Love (2015)                    0.000 0.000  ...  0.000
'burbs, The (1989)                                 0.000 0.000  ...  0.000
'night Mother (1986)                               0.000 0.000  ...  0.000
(500) Days of Summer (2009)                        0.000 0.000  ...  0.000
*batteries not included (1987)                     0.000 0.000  ...  0.000
...All the Marbles (1981)                          0.000 0.000  ...  0.000
...And Justice for All (1979)                      0.000 0.000  ...  0.000
00 Schneider - Jagd auf Nihil Baxter (1994)        0.000 0.000  ...  0.000
1-900 (06) (1994)                                  0.000 0.000  ...  0.000
10 (1979)                                          0.000 0.000  ...  0.000
10 Cent Pistol (2015)                              0.000 0.000  ...  0.000
10 Cloverfield Lane (2016)                         0.000 0.000  ...  0.000
10 Items or Less (2006)                            0.000 0.000  ...  0.000
10 Things I Hate About You (1999)                  0.000 0.000  ...  0.000
10 Years (2011)                                    0.000 0.000  ...  0.000
10,000 BC (2008)                                   0.000 0.000  ...  0.000
100 Girls (2000)                                   0.000 0.000  ...  0.000
100 Streets (2016)                                 0.000 0.000  ...  0.000
101 Dalmatians (1996)                              0.000 0.000  ...  0.000
101 Dalmatians (One Hundred and One Dalmatians)... 0.000 0.000  ...  0.000
101 Dalmatians II: Patch's London Adventure (2003) 0.000 0.000  ...  0.000
101 Reykjavik (101 ReykjavÃ­k) (2000)              0.000 0.000  ...  0.000
102 Dalmatians (2000)                              0.000 0.000  ...  0.000
10th & Wolf (2006)                                 0.000 0.000  ...  0.000
10th Kingdom, The (2000)                           0.000 0.000  ...  0.000
...                                                  ...   ...  ...    ...
Zero Dark Thirty (2012)                            0.000 0.000  ...  0.000
Zero Effect (1998)                                 0.000 0.000  ...  0.000
Zero Theorem, The (2013)                           0.000 0.000  ...  0.000
Zero de conduite (Zero for Conduct) (ZÃ©ro de c... 0.000 0.000  ...  0.000
Zeus and Roxanne (1997)                            0.000 0.000  ...  0.000
Zipper (2015)                                      0.000 0.000  ...  0.000
Zodiac (2007)                                      0.000 0.000  ...  0.000
Zombeavers (2014)                                  0.000 0.000  ...  0.000
Zombie (a.k.a. Zombie 2: The Dead Are Among Us)... 0.000 0.000  ...  0.000
Zombie Strippers! (2008)                           0.000 0.000  ...  0.000
Zombieland (2009)                                  0.000 0.000  ...  0.000
Zone 39 (1997)                                     0.000 0.000  ...  0.000
Zone, The (La Zona) (2007)                         0.000 0.000  ...  0.000
Zookeeper (2011)                                   0.000 0.000  ...  0.000
Zoolander (2001)                                   0.000 0.000  ...  0.000
Zoolander 2 (2016)                                 0.000 0.000  ...  0.000
Zoom (2006)                                        0.000 0.000  ...  0.000
Zoom (2015)                                        0.000 0.000  ...  0.000
Zootopia (2016)                                    0.000 0.000  ...  4.500
Zulu (1964)                                        0.000 0.000  ...  0.000
Zulu (2013)                                        0.000 0.000  ...  0.000
[REC] (2007)                                       0.000 0.000  ...  0.000
[REC]Â² (2009)                                     0.000 0.000  ...  0.000
[REC]Â³ 3 GÃ©nesis (2012)                          0.000 0.000  ...  0.000
anohana: The Flower We Saw That Day - The Movie... 0.000 0.000  ...  0.000
eXistenZ (1999)                                    0.000 0.000  ...  0.000
xXx (2002)                                         1.000 0.000  ...  0.000
xXx: State of the Union (2005)                     0.000 0.000  ...  0.000
Â¡Three Amigos! (1986)                             0.000 0.000  ...  0.000
Ã€ nous la libertÃ© (Freedom for Us) (1931)        0.000 0.000  ...  0.000

userId                                               602   603   604   605  \
title
'71 (2014)                                         0.000 0.000 0.000 0.000
'Hellboy': The Seeds of Creation (2004)            0.000 0.000 0.000 0.000
'Round Midnight (1986)                             0.000 0.000 0.000 0.000
'Salem's Lot (2004)                                0.000 0.000 0.000 0.000
'Til There Was You (1997)                          0.000 0.000 0.000 0.000
'Tis the Season for Love (2015)                    0.000 0.000 0.000 0.000
'burbs, The (1989)                                 0.000 0.000 0.000 0.000
'night Mother (1986)                               0.000 0.000 0.000 0.000
(500) Days of Summer (2009)                        0.000 0.000 0.000 0.000
*batteries not included (1987)                     0.000 0.000 0.000 0.000
...All the Marbles (1981)                          0.000 0.000 0.000 0.000
...And Justice for All (1979)                      0.000 0.000 0.000 0.000
00 Schneider - Jagd auf Nihil Baxter (1994)        0.000 0.000 0.000 0.000
1-900 (06) (1994)                                  0.000 0.000 0.000 0.000
10 (1979)                                          0.000 0.000 0.000 0.000
10 Cent Pistol (2015)                              0.000 0.000 0.000 0.000
10 Cloverfield Lane (2016)                         0.000 0.000 0.000 0.000
10 Items or Less (2006)                            0.000 0.000 0.000 0.000
10 Things I Hate About You (1999)                  0.000 3.000 0.000 5.000
10 Years (2011)                                    0.000 0.000 0.000 0.000
10,000 BC (2008)                                   0.000 0.000 0.000 0.000
100 Girls (2000)                                   0.000 0.000 0.000 0.000
100 Streets (2016)                                 0.000 0.000 0.000 0.000
101 Dalmatians (1996)                              0.000 4.000 0.000 3.000
101 Dalmatians (One Hundred and One Dalmatians)... 0.000 0.000 0.000 0.000
101 Dalmatians II: Patch's London Adventure (2003) 0.000 0.000 0.000 0.000
101 Reykjavik (101 ReykjavÃ­k) (2000)              0.000 0.000 0.000 0.000
102 Dalmatians (2000)                              0.000 0.000 0.000 3.000
10th & Wolf (2006)                                 0.000 0.000 0.000 0.000
10th Kingdom, The (2000)                           0.000 0.000 0.000 1.000
...                                                  ...   ...   ...   ...
Zero Dark Thirty (2012)                            0.000 0.000 0.000 0.000
Zero Effect (1998)                                 0.000 5.000 0.000 0.000
Zero Theorem, The (2013)                           0.000 0.000 0.000 0.000
Zero de conduite (Zero for Conduct) (ZÃ©ro de c... 0.000 0.000 0.000 0.000
Zeus and Roxanne (1997)                            0.000 0.000 0.000 0.000
Zipper (2015)                                      0.000 0.000 0.000 0.000
Zodiac (2007)                                      0.000 0.000 0.000 0.000
Zombeavers (2014)                                  0.000 0.000 0.000 0.000
Zombie (a.k.a. Zombie 2: The Dead Are Among Us)... 0.000 0.000 0.000 0.000
Zombie Strippers! (2008)                           0.000 0.000 0.000 0.000
Zombieland (2009)                                  0.000 0.000 0.000 0.000
Zone 39 (1997)                                     0.000 0.000 0.000 0.000
Zone, The (La Zona) (2007)                         0.000 0.000 0.000 0.000
Zookeeper (2011)                                   0.000 0.000 0.000 0.000
Zoolander (2001)                                   0.000 0.000 0.000 0.000
Zoolander 2 (2016)                                 0.000 0.000 0.000 0.000
Zoom (2006)                                        0.000 0.000 0.000 2.500
Zoom (2015)                                        0.000 0.000 0.000 0.000
Zootopia (2016)                                    0.000 0.000 0.000 0.000
Zulu (1964)                                        0.000 0.000 0.000 0.000
Zulu (2013)                                        0.000 0.000 0.000 0.000
[REC] (2007)                                       0.000 0.000 0.000 0.000
[REC]Â² (2009)                                     0.000 0.000 0.000 0.000
[REC]Â³ 3 GÃ©nesis (2012)                          0.000 0.000 0.000 0.000
anohana: The Flower We Saw That Day - The Movie... 0.000 0.000 0.000 0.000
eXistenZ (1999)                                    0.000 5.000 0.000 0.000
xXx (2002)                                         0.000 0.000 0.000 0.000
xXx: State of the Union (2005)                     0.000 0.000 0.000 0.000
Â¡Three Amigos! (1986)                             0.000 0.000 0.000 0.000
Ã€ nous la libertÃ© (Freedom for Us) (1931)        0.000 0.000 0.000 0.000

userId                                               606   607   608   609  \
title
'71 (2014)                                         0.000 0.000 0.000 0.000
'Hellboy': The Seeds of Creation (2004)            0.000 0.000 0.000 0.000
'Round Midnight (1986)                             0.000 0.000 0.000 0.000
'Salem's Lot (2004)                                0.000 0.000 0.000 0.000
'Til There Was You (1997)                          0.000 0.000 0.000 0.000
'Tis the Season for Love (2015)                    0.000 0.000 0.000 0.000
'burbs, The (1989)                                 0.000 0.000 0.000 0.000
'night Mother (1986)                               0.000 0.000 0.000 0.000
(500) Days of Summer (2009)                        0.000 0.000 0.000 0.000
*batteries not included (1987)                     0.000 0.000 0.000 0.000
...All the Marbles (1981)                          0.000 0.000 0.000 0.000
...And Justice for All (1979)                      0.000 0.000 0.000 0.000
00 Schneider - Jagd auf Nihil Baxter (1994)        0.000 0.000 0.000 0.000
1-900 (06) (1994)                                  0.000 0.000 0.000 0.000
10 (1979)                                          0.000 0.000 0.000 0.000
10 Cent Pistol (2015)                              0.000 0.000 0.000 0.000

In [77]:
from sklearn.neighbors import NearestNeighbors
model_knn = NearestNeighbors(metric='cosine',algorithm = 'brute')
model_knn.fit(rating_with_totalRating_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [131]:
query_index = np.random.choice(rating_with_totalRating_pivot.shape[0])
distances, indices = model_knn.kneighbors(rating_with_totalRating_pivot.iloc[query_index, :].values.reshape(1, -1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(rating_with_totalRating_pivot.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, rating_with_totalRating_pivot.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for Taxi to the Dark Side (2007):

1: Who Killed Chea Vichea? (2010), with distance of 0.0:
2: Burma VJ: Reporting from a Closed Country (Burma VJ: Reporter i et lukket land) (2008), with distance of 0.0:
3: Army of Shadows (L'armÃ©e des ombres) (1969), with distance of 0.0:
4: Devil Dog: The Hound of Hell (1978), with distance of 0.0:
5: First Reformed (2017), with distance of 0.0: